### ISSUE TITLE
Most recent upgrade breaks instantly on property 'unlocked'

### ISSUE THREAD

**Issue by mio-moto** [dwhalen/linearKittens#10]
```
Uncaught TypeError: Cannot read property 'unlocked' of undefined
    at getBuildingResearchButtons     (https://rawgit.com/dwhalen/linearKittens/master/linearKittens.js:594:14)
    at planLoop (https://rawgit.com/dwhalen/linearKittens/master/linearKittens.js:1216:16)
    at startLinearKittens (https://rawgit.com/dwhalen/linearKittens/master/linearKittens.js:1544:3)
    at <anonymous>:2:1
    at Object.InjectedScript._evaluateOn (<anonymous>:905:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)
    at Object.InjectedScript.evaluate  (<anonymous>:694:21)getBuildingResearchButtons @     linearKittens.js:594planLoop @ linearKittens.js:1216startLinearKittens @     linearKittens.js:1544(anonymous function) @     VM1227:2InjectedScript._evaluateOn @     VM771:905InjectedScript._evaluateAndWrap @     VM771:838InjectedScript.evaluate @ VM771:694
```

Retried several times with reloading the page and giving the js more time to load, but it's the same result every time.

**Comment by dwhalen** [comment]
Should be fixed now.  Thanks for pointing that out.
